export const PROPERTY_LIST_FETCHING = 'PROPERTY_LIST_FETCHING'
export const PROPERTY_LIST_FETCHING_SUCCESS = 'PROPERTY_LIST_FETCHING_SUCCESS'
export const PROPERTY_LIST_FETCHING_FAILED = 'PROPERTY_LIST_FETCHING_FAILED'

export const PROPERTY_FETCHING = 'PROPERTY_FETCHING'
export const PROPERTY_FETCHING_SUCCESS = 'PROPERTY_FETCHING_SUCCESS'
export const PROPERTY_FETCHING_FAILED = 'PROPERTY_FETCHING_FAILED'